# Generated by Django 3.1.4 on 2020-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(blank=True, db_column='aid', null=True)),
                ('created', models.IntegerField(blank=True, db_column='created', null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=500, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                ('author', models.CharField(blank=True, db_column='author', max_length=20, null=True)),
                ('mid', models.IntegerField(blank=True, db_column='mid', null=True)),
                ('pic', models.CharField(blank=True, db_column='cover', max_length=100, null=True)),
            ],
            options={
                'db_table': 'bili',
                'managed': True,
            },
        ),
    ]
