# Generated by Django 3.1.4 on 2020-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bili',
            name='pic',
            field=models.CharField(blank=True, db_column='pic', max_length=100, null=True),
        ),
    ]
