# Generated by Django 3.1.4 on 2020-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=20, unique=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=5, null=True)),
                ('c_time', models.DateTimeField(blank=True, db_column='c_time', max_length=30, null=True)),
                ('level', models.IntegerField(blank=True, db_column='level', default=0)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'login_user',
                'ordering': ['c_time'],
                'managed': True,
            },
        ),
    ]
