# Generated by Django 3.1.4 on 2020-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acfun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.CharField(blank=True, db_column='acno', max_length=20, null=True)),
                ('acerid', models.IntegerField(blank=True, db_column='acerid', null=True)),
                ('acname', models.CharField(blank=True, db_column='acname', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=40, null=True)),
                ('uploadtime', models.IntegerField(blank=True, db_column='uploadtime', null=True)),
                ('cover', models.CharField(blank=True, db_column='cover', max_length=100, null=True)),
            ],
            options={
                'db_table': 'acer',
                'managed': True,
            },
        ),
    ]
